// dllmain.cpp : Defines the entry point for the DLL application.

// ////////////////////////////////////////////////////////////////////////////////////////////////
// This file is auto generated by Visual Studio and manually simplified (pch dependencies removed).
// This file is required only and exclusively for Microsoft (R) Windows as the target platform.
// ////////////////////////////////////////////////////////////////////////////////////////////////

#define WIN32_LEAN_AND_MEAN             // Exclude rarely used components from Windows headers
// Windows header files
#include <windows.h>

BOOL APIENTRY DllMain(HMODULE hModule, DWORD  ul_reason_for_call, LPVOID lpReserved)
{
    switch (ul_reason_for_call)
    {
        case DLL_PROCESS_ATTACH:
        case DLL_THREAD_ATTACH:
        case DLL_THREAD_DETACH:
        case DLL_PROCESS_DETACH:
            break;
    }
    return TRUE;
}